name: check

on: push

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.1.13"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: fredrikaverpil/setup-pipx@v1.5

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry/virtualenvs
            .venv_pipx
          key: ${{ runner.os }}-${{ runner.arch }}-py-${{ env.PYTHON_VERSION }}-poetry-${{ env.POETRY_VERSION }}-${{ hashFiles('poetry.lock') }}

      - run: pipx install poetry==${{ env.POETRY_VERSION }}
        shell: bash

      - run: poetry install

      - run: poetry run black --check --diff src tests
      - run: poetry run isort --check --diff src tests
